// PERSONALIZE HERE:
// Replace these names with your names.
export const couple = {
  personOne: 'Joey',
  personTwo: 'Lera',
  homeBaseOne: 'Toronto',
  homeBaseTwo: 'Calgary',
}

// PERSONALIZE HERE:
// Dates use YYYY-MM-DD. These are kept for the home dashboard and quick references.
export const importantDates = {
  anniversary: '2024-12-25',
  personOneBirthday: '2004-07-25',
  personTwoBirthday: '2006-02-25',
}

// COUNTDOWN CONFIG:
// Edit event names, base dates, and messages here. Annual events automatically roll forward
// to the next upcoming anniversary or birthday.
export const countdownEvents = [
  {
    id: 'anniversary',
    name: 'Our next anniversary',
    date: '2024-12-25',
    repeats: 'yearly',
    message: 'Another full year of choosing each other, even across the distance.',
  },
  {
    id: 'lera-birthday',
    name: "Lera's birthday",
    date: '2006-02-25',
    repeats: 'yearly',
    message: 'A day for celebrating her properly, softly, and with a plan she actually loves.',
  },
  {
    id: 'joey-birthday',
    name: "Joey's birthday",
    date: '2004-07-25',
    repeats: 'yearly',
    message: 'A small marker for another year and another set of memories together.',
  },
  {
    id: 'next-trips',
    category: 'next-trip',
    name: 'Next trips and visits',
    message: 'Manually update these whenever a new flight, drive, or visit is booked.',
    trips: [
      {
        id: 'summer-visit',
        name: 'Our next visit',
        date: '2026-08-16',
        message: 'The next real hug on the calendar.',
      },
    ],
  },
]

export const memories = [
  {
    id: 'sample-1',
    title: 'The walk that became our default plan',
    date: '2026-06-08',
    location: 'Toronto',
    category: 'milestones',
    description: 'Coffee in hand, no rush, and the city feeling quieter than usual.',
    photo: '',
  },
  {
    id: 'sample-2',
    title: 'Airport goodbyes, softened by the next countdown',
    date: '2026-05-19',
    location: 'Calgary',
    category: 'trips',
    description: 'A small hard moment made easier because the next visit was already real.',
    photo: '',
  },
  {
    id: 'sample-3',
    title: 'Two time zones, one movie',
    date: '2026-04-26',
    location: 'Long distance',
    category: 'calls',
    description: 'Paused at the same scenes, laughed at the same lines, stayed up too late.',
    photo: '',
  },
  {
    id: 'sample-4',
    title: 'The tiny gift that made the whole week easier',
    date: '2026-03-12',
    location: 'Toronto to Calgary',
    category: 'gifts',
    description: 'A small package, a smaller note, and the exact kind of care that travels well.',
    photo: '',
  },
  {
    id: 'sample-5',
    title: 'Our first serious travel plan',
    date: '2026-02-02',
    location: 'FaceTime',
    category: 'firsts',
    description: 'Tabs open, dates circled, and both of us pretending not to be too excited.',
    photo: '',
  },
  {
    id: 'sample-6',
    title: 'The joke that would not leave',
    date: '2026-01-18',
    location: 'Voice note',
    category: 'funny moments',
    description: 'One throwaway line became a private language for the rest of the month.',
    photo: '',
  },
]

export const notes = [
  {
    id: 'sample-note-1',
    message: 'How your voice can make a regular night feel like coming home.',
    author: 'Joey',
    dateTime: '2026-06-20T21:18',
    mood: 'soft',
  },
  {
    id: 'sample-note-2',
    message: 'I am proud of how we keep choosing patience, softness, and the next plan.',
    author: 'Lera',
    dateTime: '2026-06-12T23:04',
    mood: 'proud',
  },
  {
    id: 'sample-note-3',
    message: 'Saving this here because I want us to remember the ordinary days too.',
    author: 'Joey',
    dateTime: '2026-05-28T19:42',
    mood: 'grateful',
  },
  {
    id: 'sample-note-4',
    message: 'Next airport hug is already one of my favourite future things.',
    author: 'Lera',
    dateTime: '2026-05-03T10:16',
    mood: 'missing you',
  },
]

export const bucketList = [
  { id: 1, label: 'Weekend in Banff', complete: false },
  { id: 2, label: 'Toronto island picnic', complete: true },
  { id: 3, label: 'Cook the same dinner on FaceTime', complete: true },
  { id: 4, label: 'Make a photo book', complete: false },
  { id: 5, label: 'Find our favourite airport snack', complete: false },
]

export const albumPhotos = [
  {
    id: 'photo-1',
    image: 'linear-gradient(135deg, #0f3f49, #789b85)',
    caption: 'Boarding passes and a countdown that finally reached zero.',
    date: '2026-05-19',
    category: 'trips',
  },
  {
    id: 'photo-2',
    image: 'linear-gradient(135deg, #2a6772, #9dd8c7)',
    caption: 'Coffee, city air, and nowhere urgent to be.',
    date: '2026-06-08',
    category: 'dates',
  },
  {
    id: 'photo-3',
    image: 'linear-gradient(135deg, #789b85, #f2c982)',
    caption: 'A quiet dinner that felt like its own little tradition.',
    date: '2026-04-14',
    category: 'little moments',
  },
  {
    id: 'photo-4',
    image: 'linear-gradient(135deg, #17363a, #d9eee6)',
    caption: 'Two cities, one call, and a screenshot worth saving.',
    date: '2026-03-29',
    category: 'calls',
  },
  {
    id: 'photo-5',
    image: 'linear-gradient(135deg, #0f3f49, #f2c982)',
    caption: 'The small package that made the distance feel less loud.',
    date: '2026-03-12',
    category: 'gifts',
  },
  {
    id: 'photo-6',
    image: 'linear-gradient(135deg, #9dd8c7, #fffdf8)',
    caption: 'One of those ordinary photos that becomes important later.',
    date: '2026-02-22',
    category: 'milestones',
  },
]

export const memoryMapPins = [
  {
    id: 'pin-toronto-coffee',
    placeName: 'Toronto coffee walk',
    date: '2026-06-08',
    locationQuery: 'Downtown Toronto, Ontario',
    latitude: 43.6532,
    longitude: -79.3832,
    description: 'A city walk that felt calm, familiar, and very us.',
    photo: '',
    memoryType: 'dates',
  },
  {
    id: 'pin-yyz',
    placeName: 'Toronto airport goodbye',
    date: '2026-05-19',
    locationQuery: 'Toronto Pearson International Airport',
    latitude: 43.6777,
    longitude: -79.6248,
    description: 'One of those hard airport moments made softer by the next plan.',
    photo: '',
    memoryType: 'trips',
  },
  {
    id: 'pin-calgary',
    placeName: 'Calgary visit',
    date: '2026-05-20',
    locationQuery: 'Calgary, Alberta',
    latitude: 51.0447,
    longitude: -114.0719,
    description: 'A pinned reminder that the distance has real places on both ends.',
    photo: '',
    memoryType: 'milestones',
  },
  {
    id: 'pin-banff-dream',
    placeName: 'Banff someday marker',
    date: '2026-04-02',
    locationQuery: 'Banff, Alberta',
    latitude: 51.1784,
    longitude: -115.5708,
    description: 'A future trip idea worth keeping visible on the map.',
    photo: '',
    memoryType: 'future planning',
  },
]

export const dateNightIdeas = [
  {
    id: 'cozy-1',
    title: 'Matching Pasta Night',
    category: 'cozy night in',
    estimatedTime: '60-90 min',
    needs: ['Pasta', 'Sauce', 'One shared playlist'],
    instructions: 'Cook the same pasta, plate it nicely, and rate presentation, comfort, and how much you would make it again.',
  },
  {
    id: 'cozy-2',
    title: 'Blanket Fort Movie Setup',
    category: 'cozy night in',
    estimatedTime: '2 hours',
    needs: ['Blankets', 'Snacks', 'A movie'],
    instructions: 'Build the softest possible setup, pick a comfort movie, and make phones disappear except for photos.',
  },
  {
    id: 'cozy-3',
    title: 'Tea and Tiny Goals',
    category: 'cozy night in',
    estimatedTime: '35 min',
    needs: ['Tea or hot chocolate', 'Notebook'],
    instructions: 'Make warm drinks and each write three tiny things you want from the next week. Compare gently.',
  },
  {
    id: 'cozy-4',
    title: 'Home Spa Swap',
    category: 'cozy night in',
    estimatedTime: '45 min',
    needs: ['Face masks', 'Lotion', 'Calm music'],
    instructions: 'Do a low-effort spa night and choose one small thing that helps the other person relax.',
  },
  {
    id: 'cozy-5',
    title: 'Memory Jar Night',
    category: 'cozy night in',
    estimatedTime: '40 min',
    needs: ['Paper', 'Jar or box'],
    instructions: 'Write down favourite little memories from the past month and save them for a harder day.',
  },
  {
    id: 'long-1',
    title: 'Street View Future Walk',
    category: 'long-distance date',
    estimatedTime: '45 min',
    needs: ['Video call', 'Google Maps'],
    instructions: 'Pick a neighbourhood in Toronto or Calgary and take turns choosing the next street to explore.',
  },
  {
    id: 'long-2',
    title: 'Same Recipe, Two Kitchens',
    category: 'long-distance date',
    estimatedTime: '75 min',
    needs: ['Same recipe', 'Video call'],
    instructions: 'Cook the same meal on call and compare chaos, timing, and final plates.',
  },
  {
    id: 'long-3',
    title: 'Open When Voice Notes',
    category: 'long-distance date',
    estimatedTime: '30 min',
    needs: ['Voice memo app'],
    instructions: 'Record short voice notes for specific future moods: tired, proud, missing you, nervous, excited.',
  },
  {
    id: 'long-4',
    title: 'Airport Countdown Planning',
    category: 'long-distance date',
    estimatedTime: '30 min',
    needs: ['Calendar', 'Countdown page'],
    instructions: 'Update the next trip date, plan arrival snacks, and decide the first thing you will do together.',
  },
  {
    id: 'long-5',
    title: 'Parallel Errand Date',
    category: 'long-distance date',
    estimatedTime: '60 min',
    needs: ['Headphones', 'A simple errand'],
    instructions: 'Call while each of you does an errand, then pick one tiny treat at the end.',
  },
  {
    id: 'out-1',
    title: 'Bookstore Wander',
    category: 'going out',
    estimatedTime: '60 min',
    needs: ['A bookstore', 'Coffee budget'],
    instructions: 'Pick one book for each other and one book you would read together someday.',
  },
  {
    id: 'out-2',
    title: 'Transit Coin Flip',
    category: 'going out',
    estimatedTime: '90 min',
    needs: ['Transit pass', 'Coin'],
    instructions: 'At each decision point, flip a coin for left/right or stop/continue. Find something small and new.',
  },
  {
    id: 'out-3',
    title: 'Sunset Walk',
    category: 'going out',
    estimatedTime: '45 min',
    needs: ['Comfy shoes', 'Good timing'],
    instructions: 'Walk somewhere with open sky, take one photo, and name the moment before leaving.',
  },
  {
    id: 'out-4',
    title: 'Museum One-Room Rule',
    category: 'going out',
    estimatedTime: '75 min',
    needs: ['Museum or gallery'],
    instructions: 'Visit a museum but only choose one room to really notice. Pick your favourite object and explain why.',
  },
  {
    id: 'out-5',
    title: 'Dessert First',
    category: 'going out',
    estimatedTime: '60 min',
    needs: ['Dessert place'],
    instructions: 'Go out and start with dessert. Dinner is optional; the point is to break the usual order.',
  },
  {
    id: 'food-1',
    title: 'Airport Snack Ranking',
    category: 'food',
    estimatedTime: '30 min',
    needs: ['Three snacks'],
    instructions: 'Pick three possible airport snacks and rank them for practicality, joy, and mess risk.',
  },
  {
    id: 'food-2',
    title: 'Tiny Charcuterie Challenge',
    category: 'food',
    estimatedTime: '35 min',
    needs: ['Five small foods', 'Plate'],
    instructions: 'Build the best tiny plate with only five items. Explain why each item earned its spot.',
  },
  {
    id: 'food-3',
    title: 'Breakfast for Dinner',
    category: 'food',
    estimatedTime: '45 min',
    needs: ['Breakfast ingredients'],
    instructions: 'Make breakfast at night and decide what your future lazy Sunday breakfast should be.',
  },
  {
    id: 'food-4',
    title: 'Takeout Roulette',
    category: 'food',
    estimatedTime: '45 min',
    needs: ['Delivery app or nearby restaurants'],
    instructions: 'Choose a cuisine, then each pick one item for the other person. No overthinking.',
  },
  {
    id: 'food-5',
    title: 'Family Recipe Swap',
    category: 'food',
    estimatedTime: '60-90 min',
    needs: ['A meaningful recipe'],
    instructions: 'Make or describe a recipe connected to home and tell the story that comes with it.',
  },
  {
    id: 'movie-1',
    title: 'Same-Time Movie Night',
    category: 'movies',
    estimatedTime: '2 hours',
    needs: ['Movie', 'Snacks', 'Countdown to press play'],
    instructions: 'Press play at the same time, pause once halfway, and give a dramatic halftime review.',
  },
  {
    id: 'movie-2',
    title: 'Trailer Draft',
    category: 'movies',
    estimatedTime: '30 min',
    needs: ['Movie trailers'],
    instructions: 'Watch five trailers and draft your top three. Winner picks the actual movie.',
  },
  {
    id: 'movie-3',
    title: 'Comfort Rewatch',
    category: 'movies',
    estimatedTime: '2 hours',
    needs: ['A familiar movie'],
    instructions: 'Choose something one of you already loves and explain the scenes that feel like home.',
  },
  {
    id: 'movie-4',
    title: 'Bad Movie Commentary',
    category: 'movies',
    estimatedTime: '90 min',
    needs: ['Questionable movie'],
    instructions: 'Pick a movie that might be bad and make commentary rules. Laughing is the point.',
  },
  {
    id: 'movie-5',
    title: 'Scene That Feels Like Us',
    category: 'movies',
    estimatedTime: '45 min',
    needs: ['Favourite scenes'],
    instructions: 'Each bring one scene from anything that reminds you of the relationship and explain it.',
  },
  {
    id: 'deep-1',
    title: 'Five Years, One Tuesday',
    category: 'deep questions',
    estimatedTime: '40 min',
    needs: ['Quiet space'],
    instructions: 'Describe an ordinary Tuesday together five years from now. Focus on small details.',
  },
  {
    id: 'deep-2',
    title: 'What Feels Like Care',
    category: 'deep questions',
    estimatedTime: '35 min',
    needs: ['Honest attention'],
    instructions: 'Each name three small actions that make you feel cared for and one action you want more of.',
  },
  {
    id: 'deep-3',
    title: 'Distance Check-In',
    category: 'deep questions',
    estimatedTime: '30 min',
    needs: ['Video or voice call'],
    instructions: 'Talk through what has felt easy, what has felt hard, and one adjustment for the next month.',
  },
  {
    id: 'deep-4',
    title: 'Proud Of You List',
    category: 'deep questions',
    estimatedTime: '25 min',
    needs: ['Notes app'],
    instructions: 'Write five things you are proud of in each other, then read them slowly.',
  },
  {
    id: 'deep-5',
    title: 'The Soft Boundary Talk',
    category: 'deep questions',
    estimatedTime: '35 min',
    needs: ['Patience'],
    instructions: 'Each share one boundary, one reassurance, and one way the other person can support it.',
  },
  {
    id: 'fun-1',
    title: 'Accent Interview',
    category: 'silly/fun',
    estimatedTime: '20 min',
    needs: ['Questions', 'No shame'],
    instructions: 'Interview each other in ridiculous accents and try to stay serious for at least one minute.',
  },
  {
    id: 'fun-2',
    title: 'PowerPoint About Nothing',
    category: 'silly/fun',
    estimatedTime: '45 min',
    needs: ['Slides or paper'],
    instructions: 'Each make a short presentation defending a silly opinion with unnecessary seriousness.',
  },
  {
    id: 'fun-3',
    title: 'Photo Caption Battle',
    category: 'silly/fun',
    estimatedTime: '25 min',
    needs: ['Five photos'],
    instructions: 'Pick random photos and write the funniest captions. Vote without mercy.',
  },
  {
    id: 'fun-4',
    title: 'Would You Rather Speed Round',
    category: 'silly/fun',
    estimatedTime: '20 min',
    needs: ['Timer'],
    instructions: 'Ask quick would-you-rather questions. No explaining until the end.',
  },
  {
    id: 'fun-5',
    title: 'Tiny Talent Show',
    category: 'silly/fun',
    estimatedTime: '30 min',
    needs: ['One tiny talent each'],
    instructions: 'Prepare one intentionally low-stakes talent and perform it like it matters deeply.',
  },
  {
    id: 'future-1',
    title: 'Dream Apartment Draft',
    category: 'future planning',
    estimatedTime: '45 min',
    needs: ['Pinterest or notes'],
    instructions: 'Each choose five features for a future place and compare what overlaps.',
  },
  {
    id: 'future-2',
    title: 'Trip Priority Map',
    category: 'future planning',
    estimatedTime: '35 min',
    needs: ['Map', 'Wish list'],
    instructions: 'List future trips and rank them by realistic soon, dream someday, and emotional importance.',
  },
  {
    id: 'future-3',
    title: 'Traditions We Want',
    category: 'future planning',
    estimatedTime: '30 min',
    needs: ['Notebook'],
    instructions: 'Invent five relationship traditions: one weekly, one monthly, one birthday, one travel, one silly.',
  },
  {
    id: 'future-4',
    title: 'Budget Without Panic',
    category: 'future planning',
    estimatedTime: '40 min',
    needs: ['Calculator', 'Kind tone'],
    instructions: 'Talk through one future plan and what saving for it could realistically look like.',
  },
  {
    id: 'future-5',
    title: 'Next Visit Blueprint',
    category: 'future planning',
    estimatedTime: '30 min',
    needs: ['Calendar', 'Countdown page'],
    instructions: 'Sketch the next visit: first meal, one outing, one quiet night, and one backup plan.',
  },
]
